/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#6d3bd7",
        "on-tertiary": "#1400a8",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#7c008e",
        "primary-fixed": "#e9ddff",
        "surface-dim": "#101319",
        "tertiary": "#c1c1ff",
        "on-surface-variant": "#cbc3d7",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c1c1ff",
        "surface-variant": "#32353b",
        "inverse-on-surface": "#2d3037",
        "on-surface": "#e1e2ea",
        "on-secondary-fixed": "#36003e",
        "surface-container-low": "#191c22",
        "secondary-fixed-dim": "#fbabff",
        "surface-tint": "#d0bcff",
        "outline-variant": "#494454",
        "on-primary-container": "#340080",
        "inverse-surface": "#e1e2ea",
        "secondary": "#fbabff",
        "primary-fixed-dim": "#d0bcff",
        "on-tertiary-container": "#110095",
        "on-secondary": "#580065",
        "surface-container-high": "#272a30",
        "surface": "#101319",
        "tertiary-fixed": "#e1dfff",
        "secondary-fixed": "#ffd6fd",
        "on-background": "#e1e2ea",
        "on-tertiary-fixed-variant": "#2c24ce",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#5516be",
        "secondary-container": "#ae05c6",
        "on-primary": "#3c0091",
        "surface-bright": "#363940",
        "primary": "#d0bcff",
        "surface-container-highest": "#32353b",
        "on-secondary-container": "#ffd8fd",
        "outline": "#958ea0",
        "tertiary-container": "#8183ff",
        "surface-container-lowest": "#0b0e14",
        "background": "#101319",
        "on-primary-fixed": "#23005c",
        "primary-container": "#a078ff",
        "on-tertiary-fixed": "#09006b",
        "surface-container": "#1d2026"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "topbar_height": "64px",
        "input_height": "40px",
        "sidebar_width": "260px",
        "gutter": "24px",
        "stack_gap": "12px",
        "card_padding": "20px"
      },
      fontFamily: {
        "h1": ["Inter"],
        "h2": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "code": ["Inter"],
        "body-md": ["Inter"],
        "h3": ["Inter"]
      },
      fontSize: {
        "h1": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "h2": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "code": ["13px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "h3": ["18px", {"lineHeight": "1.4", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
